/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./../src/components/mine-basic-ui/button/index.vue')['default']
    Divider: typeof import('./../src/components/mine-basic-ui/dropdown/divider.vue')['default']
    Drawer: typeof import('./../src/components/mine-basic-ui/drawer/index.vue')['default']
    Dropdown: typeof import('./../src/components/mine-basic-ui/dropdown/index.vue')['default']
    Form: typeof import('./../src/components/ma-key-value/components/form.vue')['default']
    Input: typeof import('./../src/components/mine-basic-ui/input/index.vue')['default']
    Item: typeof import('./../src/components/mine-basic-ui/dropdown/item.vue')['default']
    MaAuth: typeof import('./../src/components/ma-auth/index.vue')['default']
    MaCitySelect: typeof import('./../src/components/ma-city-select/index.vue')['default']
    MaColCard: typeof import('./../src/components/ma-col-card/index.vue')['default']
    MaDialog: typeof import('./../src/components/ma-dialog/index.vue')['default']
    MaDictCheckbox: typeof import('./../src/components/ma-dict-picker/ma-dict-checkbox.vue')['default']
    MaDictRadio: typeof import('./../src/components/ma-dict-picker/ma-dict-radio.vue')['default']
    MaDictSelect: typeof import('./../src/components/ma-dict-picker/ma-dict-select.vue')['default']
    MaDrawer: typeof import('./../src/components/ma-drawer/index.vue')['default']
    MaIconPanel: typeof import('./../src/components/ma-icon-picker/ma-icon-panel.vue')['default']
    MaIconPicker: typeof import('./../src/components/ma-icon-picker/index.vue')['default']
    MaKeyValue: typeof import('./../src/components/ma-key-value/index.vue')['default']
    MaRemoteSelect: typeof import('./../src/components/ma-remote-select/index.vue')['default']
    MaRemoteSfcLoader: typeof import('./../src/components/ma-remote-sfc-loader/index.vue')['default']
    MaResourcePicker: typeof import('./../src/components/ma-resource-picker/index.vue')['default']
    MaSelectTable: typeof import('./../src/components/ma-select-table/index.vue')['default']
    MaSvgIcon: typeof import('./../src/components/ma-svg-icon/index.vue')['default']
    MaTree: typeof import('./../src/components/ma-tree/index.vue')['default']
    MaUploadFile: typeof import('./../src/components/ma-upload-file/index.vue')['default']
    MaUploadImage: typeof import('./../src/components/ma-upload-image/index.vue')['default']
    MaVerifyCode: typeof import('./../src/components/ma-verify-code/index.vue')['default']
    Modal: typeof import('./../src/components/mine-basic-ui/modal/index.vue')['default']
    Panel: typeof import('./../src/components/ma-resource-picker/panel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Switch: typeof import('./../src/components/mine-basic-ui/switch/index.vue')['default']
    Tab: typeof import('./../src/components/mine-basic-ui/tab/index.vue')['default']
    Textarea: typeof import('./../src/components/mine-basic-ui/textarea/index.vue')['default']
    Tooltip: typeof import('./../src/components/mine-basic-ui/tooltip/index.vue')['default']
  }
}
